import TextColor from "./textColor";

const formatCodes = {
  [TextColor.Black]: "§0",
  [TextColor.DarkBlue]: "§1",
  [TextColor.DarkGreen]: "§2",
  [TextColor.DarkAqua]: "§3",
  [TextColor.DarkRed]: "§4",
  [TextColor.DarkPurple]: "§5",
  [TextColor.Gold]: "§6",
  [TextColor.Gray]: "§7",
  [TextColor.DarkGray]: "§8",
  [TextColor.Blue]: "§9",
  [TextColor.Green]: "§a",
  [TextColor.Aqua]: "§b",
  [TextColor.Red]: "§c",
  [TextColor.LightPurple]: "§d",
  [TextColor.Yellow]: "§e",
  [TextColor.White]: "§f",
  [TextColor.MinecoinGold]: "§g",
  [TextColor.MaterialQuartz]: "§h",
  [TextColor.MaterialIron]: "§i",
  [TextColor.MaterialNetherite]: "§j",
  obfuscated: "§k",
  bold: "§l",
  [TextColor.MaterialRedstone]: "§m",
  [TextColor.MaterialCopper]: "§n",
  italic: "§o",
  [TextColor.MaterialGold]: "§p",
  [TextColor.MaterialEmerald]: "§q",
  reset: "§r",
  [TextColor.MaterialDiamond]: "§s",
  [TextColor.MaterialLapis]: "§t",
  [TextColor.MaterialAmethyst]: "§u",
};

export default formatCodes;
